### ISSUE TITLE
Readme File

### ISSUE THREAD

**Issue by ajasathia** [bonham000/react-quiz-app#1]
Hi, Can you please provide readme so that its easier to configure env. and make it run on heroku?
Thanks

**Comment by bonham000** [comment]
Sure, I just added a basic `README`. It's been ages since I worked on this, so I may have missed something there but hopefully I covered enough to be helpful.

However, I created this really early on and there's a lot of new approaches now, so this code is generally a little outdated.

Also, I later refactored this app into one specifically for FCC, which has some cool features and I think the code is much cleaner. Take a look here: https://fcc-quiz.surge.sh/practice/JavaScript-Quiz/Understanding-block-scoping-with-let. I would probably look at that code more closely than the code here.

Good luck!
